#!/bin/sh

error()
{
   echo "publish: $*" >&2
   exit 1
}

INPUT_FILE=$1

[ -r ${INPUT_FILE} ] || error "Can't read ${INPUT_FILE}"

cat <<'END_OF_HEADER'
%% basic_stats.def
%
% Basic stats for the Role-Playing Game Module class
%
% Copyright 2016 Michael C. Davis
%
% LICENSE FOR THE WORK
%
% This work consists of the following files:
%    rpg_module.cls
%    basic_stats.sty
%    basic_stats.def
%    doc/rpg_module.tex
%
% This work may be distributed and/or modified under the conditions of the LaTeX
% Project Public License, either version 1.3 of this license or (at your option)
% any later version. The latest version of this license can be found at:
% http://www.latex-project.org/lppl.txt
% and version 1.3 or later is part of all distributions of LaTeX version
% 2005/12/01 or later.
%
% This work has the LPPL maintenance status `author-maintained'.
% 
% The Author and Maintainer of this work is Michael C. Davis
%
%
% OPEN GAME LICENSE
%
% The monster stats in this file are copyright 2000, Wizards of the Coast, Inc.
% and are distributed with permission under the terms of the Open Game License v 1.0.
% See the file rpg_module.cls or the compiled documentation file rpg_module.pdf for
% the full text of the license.
%
%
% LICENSE FOR COMPILED WORKS
%
% You may distribute compiled works generated using the work as specified in
% Clause 3 of the LaTeX Project Public License. If you incorporate Open Gaming
% Content into the compiled work, you must also comply with the terms of that
% license.
%
%
% USAGE
%
% See the file rpg_module.pdf (source file doc/rpg_module.tex) for documentation. 
% There are a number of worked examples in the examples/ directory.
%
% Technical support is provided on Dragonsfoot Forums:
%
% http://www.dragonsfoot.org/forums/viewtopic.php?f=87&t=73823


END_OF_HEADER

awk 'BEGIN{ FS="|"; }
{
   if(NR == 1) next;
   printf("\\monster%s{%s}{%s}{%s", $3, $1, $2, $4);
   for(i = 5; i <= NF; ++i) printf("|%s", $i);
   printf("}\n");
}' ${INPUT_FILE}
